### ISSUE TITLE
make gh issues for 4s event

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#1]
1. Copy action items and deliverables from https://docs.google.com/document/d/1AMkWFA-4I6y1_IpG_heVxqaDMFB3YxPDuZ966NzXcsA/edit# and assign to people
2. Set up a waffle board

**Comment by flyingzumwalt** [comment]
- Make sure we have people who can help participants use command line on Windows
- Identify "station" leads for hands-on

**Comment by ebarry** [comment]
Where's the waffle? <3

**Comment by flyingzumwalt** [comment]
https://waffle.io/datatogether/learning
