### ISSUE TITLE
Invite Boston-based collaborators

### ISSUE THREAD

**Issue by dcwalk** [datatogether/learning#11]
We know there are some Boston-based Data Together people (cc @jeffreyliu) or those that are interested in participating/learning more (@titaniumbones). 

We should reach out directly about attending the [event](https://envirodatagov.org/edgi-at-4s/)

**Comment by b5** [comment]
Angela Chang on the archivers slack has volunteered to help with windows work (yay!)

**Comment by dcwalk** [comment]
We've done what is possible here! Closing
