### ISSUE TITLE
Pre-Workshop Survey for Workshop Attendees

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#2]
Post a survey for workshop attendees to fill out in advance. When ready, send out an email inviting attendees to fill it out.

Questions:
What datasets do you rely on? _keywords + 2 or 3 URLs_

**Comment by b5** [comment]
Ok! Initial form is stored to the Data Together Google drive. public link: https://goo.gl/forms/elysygzSvsrhRjgf2

**Comment by dcwalk** [comment]
Hey I can't access the form! I get "You need permission"

**Comment by dcwalk** [comment]
This is covered in #3, a draft of which is here: https://hackmd.io/AwRgZgLATAxgbAIwLQHYTDEiKwiQTgFNgUsAOAQwFZKJgpgz8g==#

**Comment by dcwalk** [comment]
This has been done as of last night!

**Comment by dcwalk** [comment]
This was sent out Aug 19-20, with one more email scheduled for send out before the event!
