### ISSUE TITLE
Privacy of user information on Data Together

### ISSUE THREAD

**Issue by mhucka** [datatogether/learning#22]
If someone signs up on archivers.co, there is currently no explanation of a privacy and security policy. We should probably have one.

There are probably plenty of starting points. Here's one I wrote for something else, to give us some ideas about the topics that probably should be discussed: http://sbml.org/Facilities/Documentation/Privacy_notice_and_terms_of_service_for_the_Online_SBML_Validator

Also, such things typically need to be vetted by lawyers (or at least that's a requirement whenever I put up an online service at my institution – might be different in this context).

**Comment by dcwalk** [comment]
@mhucka -- is this a tutorial or something that would have to be more broadly a doc about Data Together? (We might want to open a parallel issue in the main repo?)

**Comment by mhucka** [comment]
@dcwalk This was sparked by working on the tutorial, but indeed I meant this about datatogether.org. I think the tutorial doesn't have to be explicit about this – kind of outside the scope. And you're right that this issue should be filed elsewhere. Which repo would be the right one?

**Comment by dcwalk** [comment]
I think https://github.com/datatogether/datatogether... I've moved there and will close here for now: https://github.com/datatogether/datatogether/issues/9
