### ISSUE TITLE
Advance Packet for 4S Workshop Attendees

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#3]
Prepare advance packet for workshop attendees and send it out.

Draft of Pre-materials to send out: 

- Join Slack, get it on your computer / phone
- Visit datatogether.org?
- Read EDGI Blog post on “introducing data together”?
- Be aware that there will be a followup google form request about what data you rely on, and who you reached out to about it, and what you talked about. 
- Fill out RSVP survey (see #2)

Supplies to bring:

- people could bring their own hardware? if so, what requirements?

**Comment by b5** [comment]
I'm assuming you mean 4S ;)

Would it make sense to post this up as a page on the data together static site? We could have it be datatogether.org/4s-workshop, that gets people on datatogether.org in the first place

Also, could the survey from #2 be added to this list? If so I'd be happy to rough out a PR with this page in the datatogether/website repo.

**Comment by flyingzumwalt** [comment]
good catch. thank you. yeah. both of your suggestions sound good to me.

**Comment by dcwalk** [comment]
Talking on check-in call Aug 13, 2017:
- This primarily will go out as an email on Thurs Aug 17
- Also served as a static site (stretch goal!!!) Updated with the same text

"Thank you for participating in the Data Together Workshop, we are all experimenting on this together" (not the expectation of a perfect experience into being a contributor to improve how this works)

**Comment by dcwalk** [comment]
@b5 -- will merge in based on copy: https://github.com/datatogether/website/pull/13

**Comment by dcwalk** [comment]
A first attempt at a draft here: https://hackmd.io/AwRgZgLATAxgbAIwLQHYTDEiKwiQTgFNgUsAOAQwFZKJgpgz8g==#

**Comment by dcwalk** [comment]
Worked on this on Thursday, was sent out last night! Closing :)

**Comment by dcwalk** [comment]
This was sent out Aug 19-20, with one more email scheduled for send out before the event!
