### ISSUE TITLE
Pre-Harvest URLs identified in RSVP responses for Workshop

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#4]
Pre-Harvest URLs identified in RSVP responses, so people have something to find & replicate in the tutorials.

**Comment by b5** [comment]
@dcwalk update: we haven't had any new entries, so our anon list in the google drive should represent all of the stuff we have currently. Some of it is "vague", total number of entries is under 10.

**Comment by dcwalk** [comment]
Great! Marking as done :)
