### ISSUE TITLE
Tutorial: Nominate a dataset to Data Together 

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#5]
Write a tutorial, modeled on the dweb primer, showing how to add a dataset to Data Together

Things to address in addition to the _how_:
- how is this an example of stewarding Data Together?
- what happens when I nominate a dataset?
- can I harvest a dataset myself?
- can my community run their own data together harvester and storage nodes?

**Comment by flyingzumwalt** [comment]
depends on https://github.com/datatogether/roadmap/issues/22

**Comment by flyingzumwalt** [comment]
proofreaders: @ebarry @mhucka

**Comment by dcwalk** [comment]
Taken a first pass, you can see it in this branch: https://github.com/datatogether/learning/tree/gitbook-init

**Comment by dcwalk** [comment]
Had a brief demo with @b5 on Aug 14:

- Prelim thoughts/notes:
  - "Add a Dataset" is this the right language? 
    - "Add" versus "Nominate"? (we want mark that something is important? How to capture that?
  - "Archive a URL" -> this should be the **file** _ 
    - (side note: should work if you post a landing page to crawl, _but_ lots of questions opened up about crawl params, storage constraints)
  - Paste into text box
  - Press "Archive"
- Metadata Entry? What do we want then 
  - Same page as upload vs. after?
  - Metadata about a group/persons engagement with that data, versus
  - Metadata about the dataset itself

**Comment by dcwalk** [comment]
FYI I'm blocked by issues I've laid out in https://github.com/datatogether/context/pull/45

**Comment by dcwalk** [comment]
Oops, I don't think this should be closed yet as we still haven't got a draft out :/

**Comment by dcwalk** [comment]
@ebarry and @mhucka were amazing collaborators on this, we have an iteration for the workshop, closing!
