### ISSUE TITLE
Tutorial: Replicate a dataset you care about onto hardware that you control 

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#7]
Write a tutorial, based on the style of the dweb primer, showing how to replicate a dataset.

General steps
1. Install ipfs
2. Make sure ipfs is installed and working properly
3. get the hash of the data
4. Make sure you have enough storage space to hold the data
5. pin the data onto your machine.

Follow-up info:
- Pinning rings, ipfs-cluster, and pinning services
- A recommendation for libraries to run ipfs nodes and to treat pin sets as part of their collections, and to treat nomination of datasets for harvest/replication as part of collection development activities.

**Comment by mhucka** [comment]
@flyingzumwalt During one of the past telecons, IIRC you had pointed to a past tutorial (it might have been on installing IPFS?) that could be used as a model here. Could you repost the link here?

**Comment by flyingzumwalt** [comment]
Yeah. @dcwalk added the links to the [4S workshop planning notes](https://docs.google.com/document/d/1AMkWFA-4I6y1_IpG_heVxqaDMFB3YxPDuZ966NzXcsA/edit#)

Examples of Tutorials:
Decentralized Web Primer - Files on IPFS tutorial: [source/markdown](https://github.com/flyingzumwalt/decentralized-web-primer/tree/master/files-on-ipfs) and [rendered pages](https://dweb-primer.ipfs.io/files-on-ipfs/)

There's a bit of background/explanation about this format at https://dweb-primer.ipfs.io/#format

Also see reverse instructional design reference: https://swcarpentry.github.io/instructor-training/

**Comment by dcwalk** [comment]
@ebarry and @mhucka were amazing collaborators on this, we have an iteration for the workshop, closing!
