### ISSUE TITLE
identify hands-on track leaders

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/learning#8]
Identify people to be "station" leads for the hands-on portion of the workshop.

_Must make sure we have people who can help participants use command line on Windows_

* using the command line (must be prepared to support windows, mac and linux)
* installing IPFS
* finding the hash you want to replicate and making sure you have enough storage
* pinning the data on you ipfs node
* playing with the pinned copy of the data

Note: We know that some people won't get past station 1. That's ok. Getting exposure to the command line in an encouraging, supportive environment is an extremely valuable and empowering learning experience.

**Comment by flyingzumwalt** [comment]
@jeffreyliu can you help us find people to be station leads?

**Comment by jeffreyliu** [comment]
Yes, how many leads do you think will be needed?

**Comment by ebarry** [comment]
We don't have a strict number because we're not sure how many of the 75 respondents will show up on the day of, and of them, we don't know how many will join our track. With those caveats, i think 4-6 solid track leaders would be great --> it would mean that ~ 20 participants would work in groups of 4, and each group would have a track leader. How does that sound?

**Comment by flyingzumwalt** [comment]
I think it will be best for people to lead a station that focuses on a specific step or a few steps of the tutorial, ie. "using the command line on windows and getting ipfs installed on windows" rather than tracks, where a whole group goes through the whole tutorial together. This will make it easier for people to self-select into groups that fit the things they need to learn or are having trouble with.

This also makes it easier for station leads to prepare -- they should go through all of the steps of the tutorial and make sure they understand the big picture, but they get to primarily prepare to answer a constrained set of questions and tackle a limited set of technical obstacles that people might encounter.

Particular note: we especially need 1 or 2 people who will be comfortable teaching people how to use the command line on Windows. I don't think any of the workshop organizers have that particular skill set.

**Comment by ebarry** [comment]
We found one additional Windows track leader, and attracted a couple more participants through local outreach.
