### ISSUE TITLE
Design icebreaker / interactive performance

### ISSUE THREAD

**Issue by ebarry** [datatogether/learning#9]
Design icebreaker / interactive performance around an abstract concept like "where the data goes," "distributed hashtables," or other. 

Takeaway for participants: ability to see your own role in a larger ecosystem where people hold the data that they care about rather than relying on current institutions and structures

prior art by @dcwalk : https://github.com/dcwalk/performingmesh

**Comment by b5** [comment]
ok just cracked open the wonderful performing mesh repo, I want to link a few images here b/c I think there's _lots_ to be learned from le prior art:

![screen shot 2017-08-10 at 4 46 39 pm](https://user-images.githubusercontent.com/1154390/29191483-e0fce9b8-7deb-11e7-8d79-600538dc05df.png)
![screen shot 2017-08-10 at 4 46 43 pm](https://user-images.githubusercontent.com/1154390/29191485-e394d1d6-7deb-11e7-9d58-8b1947da8a23.png)
![screen shot 2017-08-10 at 4 46 46 pm](https://user-images.githubusercontent.com/1154390/29191488-e61d5158-7deb-11e7-85ba-57d4197726e4.png)

🔥 

I'd really love some more info on this @dcwalk, seems like we have a lot of people + concepts + tech stuff going on that this workshop speaks to. 

I'm wondering if there's a world where we can modify tutorial #7 to add this role-playing concept? It might help to skirt around some technical limitations (unfinished software, machine setup concerns) while showing the value of what we're doing.

*OR* is this something we should do right out the gates to show the concepts, in full summer-camp-musical steez?

Either way, seems like there's lots to learn here!

**Comment by mhucka** [comment]
This doesn't really need saying in the present company (you are all truly, wonderfully inclusive people), but I worry that people icons may be problematic because they tend to display overt gender differences (and sometimes race differences or other issues), which may perpetuate biases.  I don't know what to suggest to avoid that, except very careful choices or maybe avoiding people icons altogether.

(Sorry if I'm going overboard. In the past, I've gotten called out for choosing icons with obvious gender implications, and I hate that I made that mistake, and now I may be hypersensitive...)

**Comment by dcwalk** [comment]
Oop didn't see the most recent comment until now.

@mhucka -- I hear you about wanting to take care with gendering and racializing and how that can perpetuate unwelcome stereotypes. When selecting those icons originally @structur and I had taken care to have icons that also felt non-binary. But looking back I'm sure we could have done better.

This said, I don't believe we will have icons in the icebreaker/warm up activity, and even better, I think the illustrations that @flyingzumwalt has been using to talk about Data Together (in the Code4Lib talk for instance) are really dynamic and inclusive.

**Comment by dcwalk** [comment]
Just to drop the link to those illustrations I mentioned above: https://github.com/ipfs/artwork/tree/master/IPFS_Golden_Age_for_Libraries_illustrations

**Comment by titaniumbones** [comment]
I particularly like the "roles"  image in@b5's comment above.

**Comment by dcwalk** [comment]
haha I do too ;) @titaniumbones 

Post-event update: we went with a couple string toss examples of distributed (more like decentralized) vs. centralized networks as well as getting at content- versus location- addressing.

I'm gonna drop this other resource I had a hand in which has some ideas for activities: https://github.com/tomeshnet/tomesh.101

**Comment by dcwalk** [comment]
We did this! Whoops, I'm gonna close this :)
